# Generated by Django 5.2.3 on 2025-08-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_time',
            new_name='updated_at',
        ),
    ]
