# Generated by Django 5.2.3 on 2025-08-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_rename_creation_time_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='creation_time',
        ),
    ]
